const {SlashCommandBuilder, MessageFlags, ContainerBuilder} = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('dm')
        .setDescription('Send a direct message to a user')
        .addUserOption(option =>
            option.setName('user')
                .setDescription('The user to send the DM to')
                .setRequired(true))
        .addStringOption(option =>
            option.setName('message')
                .setDescription('The message to send')
                .setRequired(true)),
    async execute(interaction) {
        const user = interaction.options.getUser('user');
        const message = interaction.options.getString('message');

        try {
            await user.send(message);
            const dmContainer = new ContainerBuilder()
                .addTextDisplayComponents((t) =>
                    t.setContent(`## ✅ DM Sent`)
                )
                .addSeparatorComponents((s) => s)
                .addTextDisplayComponents((t) =>
                    t.setContent(`**Message sent to:** <@${user.id}>\n**Message:** ${message}`)
                )
                .addSeparatorComponents((s) => s)
                .addTextDisplayComponents((t) =>
                    t.setContent(`-# Message generated by <@${interaction.user.id}> • ${new Date().toLocaleString()}`)
                );

            await interaction.reply({
                components: [dmContainer],
                flags: MessageFlags.IsComponentsV2
            });
        } catch (error) {
            console.error(error);
            await interaction.reply({ content: 'Failed to send DM. The user may have DMs disabled.', ephemeral: true });
        }
    }
};