const {SlashCommandBuilder, ContainerBuilder, MessageFlags } = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('invoice')
        .setDescription('Generate an invoice for a completed order')
        .addStringOption(option =>
            option.setName('order-id')
                .setDescription('The ID of the completed order')
                .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('amount')
                .setDescription('The amount to be invoiced')
                .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('items')
                .setDescription('the items in the order')
                .setRequired(true)
        ),
    async execute(interaction) {
        const orderId = interaction.options.getString('order-id');
        const amount = interaction.options.getString('amount');
        const items = interaction.options.getString('items');
        const channel = interaction.channel;
        
        const invoiceContainer = new ContainerBuilder()
            .addTextDisplayComponents((t) =>
                t.setContent(`## Invoice — Order ID: ${orderId}`)
            )
            .addSeparatorComponents((s) => s)
            .addTextDisplayComponents((t) =>
                t.setContent(`**Amount:** ${amount}`)
            )
            .addTextDisplayComponents((t) =>
                t.setContent(`**Items:** ${items}`)
            )
            .addSeparatorComponents((s) => s)
            .addTextDisplayComponents((t) =>
                t.setContent(`-# Generated by <@${interaction.user.id}> • ${new Date().toLocaleString()}`)
            );

        await channel.send({
            components: [invoiceContainer],
            flags: MessageFlags.IsComponentsV2
        });
    }
};
