const {SlashCommandBuilder, MessageFlags, ContainerBuilder} = require('discord.js');
const completeOrder = require('./complete-order');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('send-file')
        .setDescription('send a completed file to the user')
        .addUserOption(option =>
            option.setName('user')
                .setDescription('The user to send the file to')
                .setRequired(true)
        )
        .addAttachmentOption(option =>
            option.setName('file')
                .setDescription('The completed file to send')
                .setRequired(true)
        ),
    async execute(interaction) {
        const user = interaction.options.getUser('user');
        const file = interaction.options.getAttachment('file');

        try {
            const sendFileContainer = new ContainerBuilder()
                .addTextDisplayComponents((t) =>
                    t.setContent(`## ✅ File Sent`)
                )
                .addSeparatorComponents((s) => s)
                .addTextDisplayComponents((t) =>
                    t.setContent(`**File sent to:** <@${user.id}>\n**File:** ${file.name}`)
                )
                .addSeparatorComponents((s) => s)
                .addTextDisplayComponents((t) =>
                    t.setContent(`-# Message generated by <@${interaction.user.id}> • ${new Date().toLocaleString()}`)
                )
                const dmContainer = new ContainerBuilder()
                .addTextDisplayComponents((t) =>
                    t.setContent(`## 📁 File Received`)
                )
                .addSeparatorComponents((s) => s)
                .addSeparatorComponents((s) => s)
                .addTextDisplayComponents((t) =>
                    t.setContent(`**File received from:** <@${interaction.user.id}>\n**File:** ${file.name}`)
                )
                .addSeparatorComponents((s) => s)
                .addTextDisplayComponents((t) =>
                    t.setContent(`-# Message sent by <@${interaction.user.id}> • ${new Date().toLocaleString()}`)
                );
                
            await user.send({components: [dmContainer], flags: MessageFlags.IsComponentsV2 });
                await user.send({ files: [file] });

            await interaction.reply({
                components: [sendFileContainer],
                flags: MessageFlags.IsComponentsV2
            });
        } catch (error) {
            console.error(error);
            await interaction.reply({ content: 'Failed to send file. The user may have DMs disabled.', ephemeral: true });
        }
    }
};