const {SlashCommandBuilder, MessageFlags, ContainerBuilder} = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('unwarn')
        .setDescription('Remove a warning from a user')
        .addUserOption(option =>
            option.setName('user')
                .setDescription('The user to remove the warning from')
                .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('reason')
                .setDescription('The reason for removing the warning')
                .setRequired(true)
        ),
    async execute(interaction) {
        const user = interaction.options.getUser('user');
        const reason = interaction.options.getString('reason');
        const channel = interaction.channel;

        const unwarnContainer = new ContainerBuilder()
            .addTextDisplayComponents((t) =>
                t.setContent(`## Warning Removed`)
            )
            .addSeparatorComponents((s) => s)
            .addTextDisplayComponents((t) =>
                t.setContent(`**User:** <@${user.id}>`)
            )
            .addTextDisplayComponents((t) =>
                t.setContent(`**Removed by:** <@${interaction.user.id}>`)
            )
            .addTextDisplayComponents((t) =>
                t.setContent(`**Reason:** ${reason}`)
            )
            .addSeparatorComponents((s) => s)
            .addTextDisplayComponents((t) =>
                t.setContent(`-# Message generated by <@${interaction.user.id}> • ${new Date().toLocaleString()}`)
            );

        await channel.send({
            components: [unwarnContainer],
            flags: MessageFlags.IsComponentsV2
        });

        await interaction.reply({ content: `Warning removed from <@${user.id}>.`, ephemeral: true });
    }
};