const {SlashCommandBuilder, ContainerBuilder, MessageFlags } = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('wip')
        .setDescription('send wip message to a channel')
    ,
    async execute(interaction) {
        const channel = interaction.channel;
        const wipContainer = new ContainerBuilder()
            .addTextDisplayComponents((t) =>
                t.setContent(`## This channel is currently a work in progress!`)
            )
            .addSeparatorComponents((s) => s)
            .addTextDisplayComponents((t) =>
                t.setContent(`**Information:** This channel is currently a work in progress. Please check back later for updates.`)
            )
            .addSeparatorComponents((s) => s)
            .addTextDisplayComponents((t) =>
                t.setContent(`-# Message generated by <@${interaction.user.id}> • ${new Date().toLocaleString()}`)
            );
            await interaction.reply({ content: 'WIP message sent!', ephemeral: true });
        await channel.send({
            components: [wipContainer],
            flags: MessageFlags.IsComponentsV2
        });
    }
};